# Generated by Django 3.0.7 on 2020-06-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200612_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='pic',
            new_name='picname',
        ),
        migrations.AddField(
            model_name='news',
            name='picurl',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='news',
            name='catname',
            field=models.CharField(max_length=50),
        ),
    ]
