# Generated by Django 3.0.7 on 2020-06-18 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200618_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='views',
            new_name='show',
        ),
    ]
