# Generated by Django 3.0.7 on 2020-06-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200610_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='fb',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='main',
            name='link',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='main',
            name='set_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='main',
            name='tel',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='main',
            name='tw',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='main',
            name='yt',
            field=models.CharField(max_length=40),
        ),
    ]
