# Generated by Django 3.0.7 on 2020-06-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200618_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='picname2',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='main',
            name='picurl2',
            field=models.TextField(default='-'),
        ),
    ]
